controller_list:
  - name: fake_arm_controller
    joints:
      - base_Link__gG_Rechts
      - gG_Rechts__gG_Links
      - mG_Links__mG_Rechts
      - mG_Rechts__oberSchwinge
      - kG_Rechts__kG_Links
      - kG_Links__endEffektor